---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines

outputs:
  - name: bats-config

run:
  path: pipelines/vcloud/tasks/prepare-bats.sh

params:
  STEMCELL_NAME:          ""
  VCLOUD_VLAN:            ""
  VCLOUD_VAPP:            ""
  NETWORK_CIDR:           ""
  NETWORK_GATEWAY:        ""
  BATS_DIRECTOR_IP:       ""
  BATS_IP1:               ""
  BATS_IP2:               ""
  BATS_RESERVED_RANGE1:   ""
  BATS_RESERVED_RANGE2:   ""
  BATS_STATIC_RANGE:      ""
  BOSH_DIRECTOR_USERNAME: ""
  BOSH_DIRECTOR_PASSWORD: ""
