---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: director-config

run:
  path: pipelines/vcloud/tasks/prepare-director.sh

params:
  VCLOUD_HOST:            ""
  VCLOUD_USER:            ""
  VCLOUD_PASSWORD:        ""
  VCLOUD_VLAN:            ""
  VCLOUD_ORG:             ""
  VCLOUD_VDC:             ""
  VCLOUD_VAPP:            ""
  VCLOUD_CATALOG:         ""
  NETWORK_CIDR:           ""
  NETWORK_GATEWAY:        ""
  BATS_DIRECTOR_IP:       ""
  BOSH_USER: ""
  BOSH_PASSWORD: ""
  SSLIP_IO_KEY:           ""
