---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-cli
  - name: deployment-manifest
  - name: pipelines
  - name: stemcell

run:
  path: pipelines/aws/tasks/create-deployment.sh

params:
  AWS_ACCESS_KEY:         ""
  AWS_SECRET_KEY:         ""
  AWS_REGION_NAME:        ""
  AWS_STACK_NAME:         ""
  BOSH_DIRECTOR_PASSWORD: ""
  BOSH_DIRECTOR_USERNAME: ""
  RELEASE_NAME:           ""
  DEPLOYMENT_NAME:        ""
