---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: stemcell
  - name: pipelines
  - name: bosh-cli

run:
  path: pipelines/aws/tasks/run-e2e.sh

params:
  BOSH_DEBUG_LEVEL: info
  AWS_ACCESS_KEY:   ""
  AWS_SECRET_KEY:   ""
  AWS_REGION_NAME:  ""
  BOSH_USER:        ""
  BOSH_PASSWORD:    ""
  AWS_STACK_NAME:   ""
  STEMCELL_NAME:    ""
