---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cli
  - name: new-director-config
  - name: old-director-state

outputs:
  - name: new-director-state

params:
  DEPLOYMENT_NAME: ""

run:
  path: pipelines/shared/tasks/test-upgrade.sh
