---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: stemcell
  - name: deployment-manifest
  - name: bosh-cli

run:
  path: pipelines/softlayer/tasks/create-deployment.sh

params:
  BOSH_CLIENT_SECRET: ""
  BOSH_CLIENT: ""
  RELEASE_NAME:           ""
  DEPLOYMENT_NAME:        ""
